# Change these first
owner: gnfi # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Good News From Indonesia
    url: https://www.goodnewsfromindonesia.id
  - name: Seasia
    url: https://seasia.co
  - name: Rekam Indonesia
    url: https://www.rekamindonesia.id
  - name: GoodSite
    url: https://goodside.id
  - name: Karier
    url: https://karier.goodnews.id/
  - name: Media Partner
    url: https://partner.goodnews.id/media

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.goodnews.id
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/gnfi/uptime/master/assets/favicon-rounded-edited.png
  name: Uptime
  introTitle: "**Uptime** adalah laman monitor status produk-produk GNFI."
  introMessage: Di laman ini kamu bisa mengecek status produk-produk GNFI, apakah bisa diakses atau kah tidak. Bila tidak bisa diakses, informasi terbaru akan segera mungkin ditampilkan di sini.
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
